spring:
  datasource:
    url: jdbc:h2:mem:formulario-db
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /formulario-h2      